package hostdns

import (
	"bytes"
	"log/slog"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const sentinel = "172.19.0.1"

func newManager(t *testing.T) (*Manager, string, string) {
	t.Helper()
	dir := t.TempDir()
	resolv := filepath.Join(dir, "resolv.conf")
	sidecar := filepath.Join(dir, "run", "resolv.conf.orig")
	return New(sentinel, sidecar, resolv, slog.New(slog.DiscardHandler)), resolv, sidecar
}

func TestCaptureReturnsUsableResolversAndSkipsTheRest(t *testing.T) {
	m, resolv, _ := newManager(t)
	// A real NixOS+NetworkManager resolv.conf: an IPv4 LAN resolver, an IPv6
	// link-local, and options. Only the IPv4 one is usable for the bootstrap pin.
	seed := "# Generated by resolvconf\nnameserver 192.168.1.1\n" +
		"nameserver fe80::52ff:20ff:febb:b624%wlp0s20f3\noptions edns0\n"
	if err := os.WriteFile(resolv, []byte(seed), 0o644); err != nil {
		t.Fatal(err)
	}
	got, err := m.Capture()
	if err != nil {
		t.Fatalf("Capture: %v", err)
	}
	if len(got) != 1 || got[0] != "192.168.1.1" {
		t.Errorf("Capture() = %v, want [192.168.1.1] (IPv6 link-local must be skipped)", got)
	}
}

func TestRedirectRestoreRoundTrips(t *testing.T) {
	m, resolv, sidecar := newManager(t)
	original := []byte("# Generated by resolvconf\nnameserver 192.168.1.1\noptions edns0\n")
	if err := os.WriteFile(resolv, original, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Capture(); err != nil {
		t.Fatalf("Capture: %v", err)
	}

	if err := m.Redirect(); err != nil {
		t.Fatalf("Redirect: %v", err)
	}
	now, _ := os.ReadFile(resolv)
	if !strings.Contains(string(now), "nameserver "+sentinel) {
		t.Errorf("after Redirect resolv.conf = %q, want it pointing at the sentinel", now)
	}
	if strings.Contains(string(now), "192.168.1.1") {
		t.Errorf("after Redirect the real resolver must be gone, got %q", now)
	}
	if _, err := os.Stat(sidecar); err != nil {
		t.Errorf("Redirect must stash a crash-safe sidecar: %v", err)
	}

	if err := m.Restore(); err != nil {
		t.Fatalf("Restore: %v", err)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, original) {
		t.Errorf("after Restore resolv.conf = %q, want the exact original %q", back, original)
	}
	if _, err := os.Stat(sidecar); !os.IsNotExist(err) {
		t.Errorf("Restore must clear the sidecar, stat err = %v", err)
	}
}

func TestRedirectIsIdempotent(t *testing.T) {
	m, resolv, _ := newManager(t)
	original := []byte("nameserver 192.168.1.1\n")
	if err := os.WriteFile(resolv, original, 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Capture(); err != nil {
		t.Fatal(err)
	}
	if err := m.Redirect(); err != nil {
		t.Fatal(err)
	}
	// A second Redirect must NOT stash the already-redirected file as the "original".
	if err := m.Redirect(); err != nil {
		t.Fatalf("second Redirect: %v", err)
	}
	if err := m.Restore(); err != nil {
		t.Fatal(err)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, original) {
		t.Errorf("double Redirect then Restore lost the original: got %q", back)
	}
}

func TestCaptureRecoversALeftoverRedirect(t *testing.T) {
	m, resolv, sidecar := newManager(t)
	// Simulate a previous run that crashed still redirected: resolv.conf holds the
	// sentinel, and the sidecar holds the true original.
	original := []byte("# Generated by resolvconf\nnameserver 192.168.1.1\n")
	if err := os.MkdirAll(filepath.Dir(sidecar), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sidecar, original, 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(resolv, []byte("nameserver "+sentinel+"\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := m.Capture()
	if err != nil {
		t.Fatalf("Capture: %v", err)
	}
	// It must capture the REAL resolver (from the recovered original), not the sentinel.
	if len(got) != 1 || got[0] != "192.168.1.1" {
		t.Errorf("Capture() after a crash = %v, want [192.168.1.1] — must not read the sentinel as real", got)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, original) {
		t.Errorf("Capture must have restored the leftover redirect, resolv.conf = %q", back)
	}
	if _, err := os.Stat(sidecar); !os.IsNotExist(err) {
		t.Errorf("recovery must consume the sidecar, stat err = %v", err)
	}
}

func TestCaptureRefusesASymlinkedResolvConf(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "real-resolv.conf")
	if err := os.WriteFile(target, []byte("nameserver 192.168.1.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	link := filepath.Join(dir, "resolv.conf")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("symlink unsupported here: %v", err)
	}
	m := New(sentinel, filepath.Join(dir, "run", "orig"), link, slog.New(slog.DiscardHandler))
	if _, err := m.Capture(); err == nil {
		t.Fatal("Capture must refuse a symlinked resolv.conf (a rewrite would break NM/resolved), got nil error")
	}
}

func TestCaptureDiscardsAStaleSidecarWhenTheLiveFileIsNotTheSentinel(t *testing.T) {
	m, resolv, sidecar := newManager(t)
	// A sidecar from an old run (network X) survives, but the network manager has
	// since rewritten resolv.conf to a NEW, correct resolver (network Y) — the live
	// file is NOT our sentinel. Capture must discard the stale sidecar and read Y,
	// not clobber Y with the old X resolver.
	if err := os.MkdirAll(filepath.Dir(sidecar), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(sidecar, []byte("nameserver 10.0.0.1\n"), 0o600); err != nil { // old network X
		t.Fatal(err)
	}
	fresh := []byte("# Generated by resolvconf\nnameserver 192.168.5.1\n") // new network Y
	if err := os.WriteFile(resolv, fresh, 0o644); err != nil {
		t.Fatal(err)
	}

	got, err := m.Capture()
	if err != nil {
		t.Fatalf("Capture: %v", err)
	}
	if len(got) != 1 || got[0] != "192.168.5.1" {
		t.Errorf("Capture() = %v, want the fresh resolver [192.168.5.1], not the stale sidecar's", got)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, fresh) {
		t.Errorf("Capture clobbered the fresh resolv.conf with a stale sidecar: %q", back)
	}
	if _, err := os.Stat(sidecar); !os.IsNotExist(err) {
		t.Errorf("a stale sidecar must be discarded, stat err = %v", err)
	}
}

func TestRestoreWithoutRedirectIsANoOp(t *testing.T) {
	m, resolv, _ := newManager(t)
	original := []byte("nameserver 192.168.1.1\n")
	if err := os.WriteFile(resolv, original, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := m.Restore(); err != nil {
		t.Errorf("Restore with nothing engaged should be a no-op, got %v", err)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, original) {
		t.Errorf("a no-op Restore must not touch resolv.conf, got %q", back)
	}
}

// A laptop's network manager rewrites resolv.conf on every link change. Trusting our
// own "already engaged" flag meant the periodic re-assert did nothing and the host
// quietly resolved through the ISP again — a silent leak of exactly the queries this
// feature protects.
func TestRedirectReassertsAfterTheSystemRewritesResolvConf(t *testing.T) {
	m, resolv, _ := newManager(t)
	if err := os.WriteFile(resolv, []byte("nameserver 192.168.1.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Capture(); err != nil {
		t.Fatal(err)
	}
	if err := m.Redirect(); err != nil {
		t.Fatal(err)
	}

	// Roam: NetworkManager replaces the file with the new network's resolver.
	cafe := []byte("# Generated by resolvconf\nnameserver 10.0.0.1\n")
	if err := os.WriteFile(resolv, cafe, 0o644); err != nil {
		t.Fatal(err)
	}
	if err := m.Redirect(); err != nil {
		t.Fatalf("re-assert: %v", err)
	}
	now, _ := os.ReadFile(resolv)
	if !strings.Contains(string(now), "nameserver "+sentinel) {
		t.Errorf("the re-assert must reinstall the sentinel, got %q", now)
	}

	// And what it restores must be the NEW network's file, not the stale home one.
	if err := m.Restore(); err != nil {
		t.Fatal(err)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, cafe) {
		t.Errorf("restore put back %q, want the network we are actually on (%q)", back, cafe)
	}
}

// Turning Lotsman off must never be the thing that breaks DNS: if the live file is no
// longer our sentinel, the system owns it now and we leave it alone.
func TestRestoreLeavesAFileThatIsNoLongerOurs(t *testing.T) {
	m, resolv, sidecar := newManager(t)
	if err := os.WriteFile(resolv, []byte("nameserver 192.168.1.1\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if _, err := m.Capture(); err != nil {
		t.Fatal(err)
	}
	if err := m.Redirect(); err != nil {
		t.Fatal(err)
	}
	// Something else took ownership while we were engaged.
	theirs := []byte("nameserver 10.0.0.1\n")
	os.WriteFile(resolv, theirs, 0o644)

	if err := m.Restore(); err != nil {
		t.Fatalf("restore: %v", err)
	}
	back, _ := os.ReadFile(resolv)
	if !bytes.Equal(back, theirs) {
		t.Errorf("restore clobbered the system's own file: got %q, want %q", back, theirs)
	}
	if _, err := os.Stat(sidecar); !os.IsNotExist(err) {
		t.Error("the stale sidecar must be dropped")
	}
}
