package zapret

import (
	"fmt"
	"strings"
)

// InitOptions ground per-instance init generation.
type InitOptions struct {
	BaseDir string // dir holding <instance>/active.sh, e.g. /opt/zapret-lotsman
	Nft     NftOptions
}

// DefaultInitOptions returns R5S-grounded defaults.
func DefaultInitOptions() InitOptions {
	return InitOptions{BaseDir: "/opt/zapret-lotsman", Nft: DefaultNftOptions()}
}

// InitName is the init.d script name for an instance: nfqws-<name>.
func InitName(in Instance) string { return "nfqws-" + sanitize(in.Name) }

// TableName is the per-instance nft table: each instance owns its own table so
// restarting one instance (to switch its strategy) never touches another.
func TableName(in Instance) string { return "inet zapret_" + sanitize(in.Name) }

// GenerateInit renders a procd init script for one instance. The script owns a
// private nft table (capture ports -> this instance's queue) and runs the
// instance's active.sh symlink with its qnum under procd respawn. Switching the
// instance's strategy = repoint active.sh + restart THIS init only.
func GenerateInit(in Instance, opts InitOptions) string {
	table := TableName(in)
	nftRules := GenerateNft([]Instance{in}, NftOptions{
		Table: table, WAN: opts.Nft.WAN, VPNServers: opts.Nft.VPNServers,
	})
	active := fmt.Sprintf("%s/%s/active.sh", opts.BaseDir, sanitize(in.Name))

	var b strings.Builder
	fmt.Fprintf(&b, "#!/bin/sh /etc/rc.common\n")
	fmt.Fprintf(&b, "# nfqws instance %q (qnum %d) — generated by Lotsman. Own nft table\n", in.Name, in.QNum)
	fmt.Fprintf(&b, "# (%s) so restarting this instance does not disturb the others.\n", table)
	b.WriteString("USE_PROCD=1\nSTART=99\nSTOP=10\n\n")
	fmt.Fprintf(&b, "ACTIVE=%s\nQNUM=%d\n\n", active, in.QNum)

	b.WriteString("install_nft() {\n")
	fmt.Fprintf(&b, "    nft delete table %s 2>/dev/null\n", table)
	b.WriteString("    nft -f - <<'NFT'\n")
	b.WriteString(nftRules)
	b.WriteString("NFT\n}\n\n")

	b.WriteString("start_service() {\n")
	b.WriteString("    install_nft\n")
	b.WriteString("    procd_open_instance\n")
	b.WriteString("    procd_set_param command \"$ACTIVE\" \"$QNUM\"\n")
	b.WriteString("    procd_set_param respawn 3 5 0\n")
	b.WriteString("    procd_set_param stdout 1\n")
	b.WriteString("    procd_set_param stderr 1\n")
	b.WriteString("    procd_close_instance\n")
	b.WriteString("}\n\n")

	b.WriteString("stop_service() {\n")
	fmt.Fprintf(&b, "    nft delete table %s 2>/dev/null\n", table)
	b.WriteString("}\n")

	return b.String()
}

// sanitize makes a name safe for nft table names and paths: lowercase, only
// [a-z0-9_].
func sanitize(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	var b strings.Builder
	for _, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	return b.String()
}
