package zapret

import (
	"fmt"
	"strings"

	"github.com/strace-me/lotsman/pkg/strategy"
)

// DefaultNfqwsPath is the nfqws binary on the R5S (Flowseal layout).
const DefaultNfqwsPath = "/opt/zapret/binaries/linux-arm64/nfqws"

// LauncherOpts scopes a discovered strategy to a service when rendering its
// launcher. blockcheck finds a bare nfqws profile (the desync args); the scope
// — which ports and domains it applies to — is an apply-time decision the
// caller makes (the failing service's ports/domains), not part of the strategy.
type LauncherOpts struct {
	NfqwsPath       string   // nfqws binary; empty = DefaultNfqwsPath
	FilterTCP       string   // e.g. "80,443"; empty = no TCP filter
	FilterUDP       string   // e.g. "443"; empty = no UDP filter
	HostlistDomains []string // scope to these domains (joined into one --hostlist-domains)
}

// RenderLauncher renders a discovered single-profile strategy (def.NFQWSArgs)
// into an nfqws launcher script in the same shape as Flowseal's <id>.sh: takes
// the queue number as $1, execs nfqws with the scoped filter, the target
// domains, and the discovered desync args. The executor symlinks this as active
// and restarts nfqws, exactly as for a pre-provisioned strategy.
//
// It errors if the definition has no NFQWSArgs (a script-backed strategy needs
// no rendering) or if no filter scope is given (an unscoped profile would
// desync all traffic).
func RenderLauncher(def strategy.Definition, opts LauncherOpts) (string, error) {
	if len(def.NFQWSArgs) == 0 {
		return "", fmt.Errorf("render %q: no NFQWSArgs (script-backed strategy)", def.ID)
	}
	if opts.FilterTCP == "" && opts.FilterUDP == "" {
		return "", fmt.Errorf("render %q: no filter scope (FilterTCP/FilterUDP both empty)", def.ID)
	}
	nfqws := opts.NfqwsPath
	if nfqws == "" {
		nfqws = DefaultNfqwsPath
	}

	var profile []string
	if opts.FilterTCP != "" {
		profile = append(profile, "--filter-tcp="+opts.FilterTCP)
	}
	if opts.FilterUDP != "" {
		profile = append(profile, "--filter-udp="+opts.FilterUDP)
	}
	if len(opts.HostlistDomains) > 0 {
		profile = append(profile, "--hostlist-domains="+strings.Join(opts.HostlistDomains, ","))
	}
	profile = append(profile, def.NFQWSArgs...)

	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	fmt.Fprintf(&b, "# Lotsman-discovered strategy %q. %s\n", def.ID, def.Notes)
	b.WriteString("# Generated by Lotsman — do not edit by hand. Usage: <id>.sh [qnum].\n")
	b.WriteString("QNUM=\"${1:-200}\"\n")
	fmt.Fprintf(&b, "N=%s\n", nfqws)
	fmt.Fprintf(&b, "exec \"$N\" --qnum=\"$QNUM\" %s\n", strings.Join(profile, " "))
	return b.String(), nil
}
