// Package scaffold writes a minimal, working starter config from nothing but a
// subscription URL — the "one button" onboarding. Everything else the client
// needs (the three standard pools, the per-service chains) now comes from the
// builtin categories and pool injection, so a starter is just: which
// subscriptions, and a handful of services pinned to a category. The output is
// deliberately commented so it doubles as a guided example the operator edits.
package scaffold

import (
	_ "embed"
	"fmt"
	"strings"
)

//go:embed recommended.yaml
var recommendedConfig []byte

// Recommended returns the curated default config shipped with Lotsman (services +
// rules on builtin categories, no creds) — first-run option (a). If subURLs are
// given they are prepended as a subscriptions block; otherwise the config ships
// without one, and the user adds a subscription later (e.g. in the app). Guaranteed
// to satisfy config.Parse (proven by the test).
func Recommended(subURLs []string) []byte {
	if len(subURLs) == 0 {
		return recommendedConfig
	}
	var b strings.Builder
	b.WriteString("subscriptions:\n")
	for i, u := range subURLs {
		fmt.Fprintf(&b, "  - { name: sub%d, url: %q, format: auto, tags: [normal], enabled: true }\n", i+1, u)
	}
	b.WriteString("\n")
	b.Write(recommendedConfig)
	return []byte(b.String())
}

// starterService is one line of the scaffold: a well-known service on a builtin
// category, with concrete domains and a probe so it works out of the box.
type starterService struct {
	name, category, probe string
	domains               []string
}

// defaults are a sane first set: the services people in Russia most often need
// unblocked, each on the category whose builtin chain (zapret -> VPN -> emergency)
// fits it. Kept short on purpose — the operator adds their own from here.
var defaults = []starterService{
	{"youtube", "streaming", "https://www.youtube.com/generate_204",
		[]string{"youtube.com", "googlevideo.com", "ytimg.com", "ggpht.com"}},
	{"discord", "messaging", "https://discord.com/api/v9/gateway",
		[]string{"discord.com", "discord.gg", "discordapp.com", "discordapp.net"}},
	{"instagram", "streaming", "https://www.instagram.com/favicon.ico",
		[]string{"instagram.com", "cdninstagram.com", "fbcdn.net"}},
}

// Starter returns a commented starter config. subURLs are the subscription
// endpoints to pull nodes from; at least one is required by the caller. The
// result is guaranteed to satisfy config.Parse (proven by the round-trip test).
func Starter(subURLs []string) []byte {
	var b strings.Builder
	b.WriteString("# Lotsman client — starter config, generated by `lotsman -init`.\n")
	b.WriteString("# Edit freely. The three standard pools (vpn_url_test, vpn_url_test_udp,\n")
	b.WriteString("# emergency_pool) and each service's escalation chain are supplied by the\n")
	b.WriteString("# builtin categories, so you do NOT need to declare them here — add a `pools:`\n")
	b.WriteString("# or a per-service `chain:` block only to override those defaults.\n\n")

	b.WriteString("subscriptions:\n")
	for i, u := range subURLs {
		// Tag the first subscription `normal` and any others too; a subscription whose
		// nodes should only be a last resort can be retagged `emergency` by hand.
		fmt.Fprintf(&b, "  - { name: sub%d, url: %q, format: auto, tags: [normal], enabled: true }\n", i+1, u)
	}
	b.WriteString("\n")

	b.WriteString("services:\n")
	for _, s := range defaults {
		fmt.Fprintf(&b, "  - name: %s\n", s.name)
		fmt.Fprintf(&b, "    category: %s\n", s.category)
		fmt.Fprintf(&b, "    probe_target: %s\n", s.probe)
		fmt.Fprintf(&b, "    domains: [%s]\n", strings.Join(s.domains, ", "))
	}
	return []byte(b.String())
}
