// Package strategycat provides a curated, structured catalog of zapret/nfqws
// DPI-desync strategy "recipes" for Lotsman.
//
// A recipe models exactly one nfqws "--new" block: an ordered set of args that
// compose into a per-target desync strategy. Recipes are sourced from
// StressOzz/Zapret-Manager and Flowseal/zapret-discord-youtube (plus the
// versions actually deployed on the Lotsman router) and are deduplicated by
// normalized arg list. See catalog.yaml (generated by gen.py) for the data.
package strategycat

import (
	_ "embed"
	"fmt"

	"gopkg.in/yaml.v3"
)

//go:embed catalog.yaml
var catalogYAML []byte

// TargetClass identifies the kind of traffic a recipe targets.
type TargetClass string

const (
	ClassDiscordTCP TargetClass = "discord_tcp"
	ClassQUIC       TargetClass = "quic"
	ClassYouTube    TargetClass = "youtube"
	ClassGeneralTLS TargetClass = "general_tls"
	ClassGames      TargetClass = "games"
	ClassOther      TargetClass = "other"
)

// Protocol is the transport a recipe operates on.
type Protocol string

const (
	ProtoTCP  Protocol = "tcp"
	ProtoUDP  Protocol = "udp"
	ProtoQUIC Protocol = "quic"
)

// Recipe is one nfqws "--new" block plus its metadata.
type Recipe struct {
	ID          string      `yaml:"id"`
	Provenance  string      `yaml:"provenance"`
	TargetClass TargetClass `yaml:"target_class"`
	Protocol    Protocol    `yaml:"protocol"`
	Techniques  []string    `yaml:"techniques"`
	NfqwsArgs   []string    `yaml:"nfqws_args"`
	Notes       string      `yaml:"notes"`
}

type catalog struct {
	Schema      int      `yaml:"schema"`
	Description string   `yaml:"description"`
	Sources     []string `yaml:"sources"`
	Recipes     []Recipe `yaml:"recipes"`
}

// Load parses the embedded catalog and returns all recipes in catalog order.
// It panics if the embedded data is malformed (it is generated and tested).
func Load() []Recipe {
	recipes, err := load()
	if err != nil {
		panic(fmt.Sprintf("strategycat: %v", err))
	}
	return recipes
}

func load() ([]Recipe, error) {
	var c catalog
	if err := yaml.Unmarshal(catalogYAML, &c); err != nil {
		return nil, fmt.Errorf("unmarshal catalog: %w", err)
	}
	return c.Recipes, nil
}

// ByClass returns the recipes whose TargetClass equals class, in catalog order.
func ByClass(class TargetClass) []Recipe {
	var out []Recipe
	for _, r := range Load() {
		if r.TargetClass == class {
			out = append(out, r)
		}
	}
	return out
}

// ByProtocol returns the recipes whose Protocol equals p, in catalog order.
func ByProtocol(p Protocol) []Recipe {
	var out []Recipe
	for _, r := range Load() {
		if r.Protocol == p {
			out = append(out, r)
		}
	}
	return out
}
