// Package strategycat provides a curated, structured catalog of zapret/nfqws
// DPI-desync strategy "recipes" for Lotsman.
//
// A recipe models exactly one nfqws "--new" block: an ordered set of args that
// compose into a per-target desync strategy. Recipes are sourced from
// StressOzz/Zapret-Manager and Flowseal/zapret-discord-youtube (plus the
// versions actually deployed on the Lotsman router) and are deduplicated by
// normalized arg list. See catalog.yaml (generated by gen.py) for the data.
package strategycat

import (
	_ "embed"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

//go:embed catalog.yaml
var catalogYAML []byte

// TargetClass identifies the kind of traffic a recipe targets.
type TargetClass string

const (
	ClassDiscordTCP TargetClass = "discord_tcp"
	ClassQUIC       TargetClass = "quic"
	ClassYouTube    TargetClass = "youtube"
	ClassGeneralTLS TargetClass = "general_tls"
	ClassGames      TargetClass = "games"
	ClassOther      TargetClass = "other"
)

// Protocol is the transport a recipe operates on.
type Protocol string

const (
	ProtoTCP  Protocol = "tcp"
	ProtoUDP  Protocol = "udp"
	ProtoQUIC Protocol = "quic"
)

// Recipe is one nfqws "--new" block plus its metadata.
type Recipe struct {
	ID          string      `yaml:"id"`
	Provenance  string      `yaml:"provenance"`
	TargetClass TargetClass `yaml:"target_class"`
	Protocol    Protocol    `yaml:"protocol"`
	Techniques  []string    `yaml:"techniques"`
	NfqwsArgs   []string    `yaml:"nfqws_args"`
	// Blocks is the MULTI-PROFILE form: a strategy that needs several nfqws
	// profiles, each with its own filter, to cover one service. Real bundles are
	// built this way — Flowseal's ALT12 treats a Google domain with one profile on
	// tcp/443, everything else with another on tcp/80,443, and QUIC with a third on
	// udp/443 — and a single-profile recipe can only ever be one of those three. It
	// was the QUIC one being missing that let a service pass its TCP probe while
	// carrying no video.
	//
	// Order is load-bearing: nfqws matches profiles first-to-last and stops, so a
	// narrow filter must precede the broad one it would otherwise be shadowed by.
	// Empty = single-profile, described by NfqwsArgs.
	Blocks [][]string `yaml:"blocks,omitempty"`
	Notes  string     `yaml:"notes"`
	// Preset is the upstream's own name for the bundle this recipe came out of —
	// "ALT12" for Flowseal. Operators reason in those names ("поставь ALT12"), not
	// in our derived ids, so showing one without the other makes the app and the
	// person talk past each other. Empty when the preset is not known, which is
	// honest: several catalog entries predate anyone recording it.
	Preset string `yaml:"preset,omitempty"`
	// Consensus counts the independent bundles shipping this exact recipe.
	// Set by pkg/strategyimport; absent (0) in the hand-curated catalog, where
	// the same fact lives in Provenance as prose.
	Consensus int `yaml:"consensus,omitempty"`
}

// AllBlocks returns the profiles this recipe composes into: its explicit Blocks,
// or the single profile in NfqwsArgs. One accessor so no consumer has to remember
// which form a recipe uses.
func (r Recipe) AllBlocks() [][]string {
	if len(r.Blocks) > 0 {
		return r.Blocks
	}
	if len(r.NfqwsArgs) == 0 {
		return nil
	}
	return [][]string{r.NfqwsArgs}
}

// AllArgs flattens every profile's arguments. For the scanners that ask "does this
// recipe reference payload X / a UDP filter / an unfillable placeholder", which are
// questions about the whole recipe rather than about one profile.
func (r Recipe) AllArgs() []string {
	if len(r.Blocks) == 0 {
		return r.NfqwsArgs
	}
	var out []string
	for _, b := range r.Blocks {
		out = append(out, b...)
	}
	return out
}

type catalog struct {
	Schema      int      `yaml:"schema"`
	Description string   `yaml:"description"`
	Sources     []string `yaml:"sources"`
	Recipes     []Recipe `yaml:"recipes"`
}

// Load parses the embedded catalog and returns all recipes in catalog order.
// It panics if the embedded data is malformed (it is generated and tested).
func Load() []Recipe {
	recipes, err := load()
	if err != nil {
		panic(fmt.Sprintf("strategycat: %v", err))
	}
	return recipes
}

func load() ([]Recipe, error) {
	var c catalog
	if err := yaml.Unmarshal(catalogYAML, &c); err != nil {
		return nil, fmt.Errorf("unmarshal catalog: %w", err)
	}
	return c.Recipes, nil
}

// ByClass returns the recipes whose TargetClass equals class, in catalog order.
func ByClass(class TargetClass) []Recipe {
	var out []Recipe
	for _, r := range Load() {
		if r.TargetClass == class {
			out = append(out, r)
		}
	}
	return out
}

// ByProtocol returns the recipes whose Protocol equals p, in catalog order.
func ByProtocol(p Protocol) []Recipe {
	var out []Recipe
	for _, r := range Load() {
		if r.Protocol == p {
			out = append(out, r)
		}
	}
	return out
}

// Origin is the name a human uses for where this recipe came from: the upstream
// bundle's own preset when the catalogue records one ("ALT12"), and otherwise the
// vendor and version compacted out of its provenance ("Flowseal 1.9.9a").
//
// It exists because the ID is OURS. `flowseal-general-multisplit-568-4pda`
// describes the technique to us and answers nothing an operator asks, which is
// "which of the strategies I know is this?". Only four of seventy recipes carry a
// preset, so a display keyed on preset alone shows the bare id for the other
// sixty-six — measured by the owner looking at gaming-battlenet and asking why
// the app would not tell him the name.
func (r Recipe) Origin() string {
	if r.Preset != "" {
		return r.Preset
	}
	p := r.Provenance
	// Everything after "(" or "|" is a parenthetical or an alternative source, not
	// the name. Dropping it also keeps a few older entries from putting a LAN
	// address on screen — those provenances need rewriting before any public
	// release regardless.
	if i := strings.IndexAny(p, "(|"); i >= 0 {
		p = p[:i]
	}
	p = strings.TrimSpace(p)
	if p == "" {
		return ""
	}
	fields := strings.Fields(p)
	// "Flowseal/zapret-discord-youtube 1.9.9a" -> vendor is the part before the
	// slash; the repository name is noise once the vendor is named.
	if i := strings.Index(fields[0], "/"); i > 0 {
		fields[0] = fields[0][:i]
	}
	if len(fields) > 2 {
		fields = fields[:2]
	}
	// Belt and braces over the data fix: a provenance that named a machine rather
	// than a vendor would otherwise put a LAN address or a filesystem path on the
	// dashboard, and this catalogue is headed for a public release. Four entries
	// did exactly that until they were rewritten; the guard stays so the next one
	// is caught by a test instead of by a screenshot.
	for _, f := range fields {
		if strings.Contains(f, "/") || looksLikeAddress(f) {
			return ""
		}
	}
	return strings.Join(fields, " ")
}

// looksLikeAddress reports a bare dotted-quad. Deliberately crude: it only has to
// recognise the shape someone types when they mean "the box in my hallway".
func looksLikeAddress(s string) bool {
	parts := strings.Split(s, ".")
	if len(parts) != 4 {
		return false
	}
	for _, p := range parts {
		if p == "" {
			return false
		}
		for _, r := range p {
			if r < '0' || r > '9' {
				return false
			}
		}
	}
	return true
}
